name: Build content

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install requirements
        run: >-
          python -m
          pip install
          -r
          requirements.txt
          --user
      - name: Run build
        run: >-
          python -m
          llama
      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build